In [1]:
import pandas as pd

In [2]:
edges = pd.read_csv('./edges.csv')
edges.head()

,source,target,type,id,label,timeset,weight,colab_track_popularity,colab_track_name,colab_track
0,Bad Bunny,Bomba Estéreo,Directed,1397,NaN,NaN,1,97,Ojitos Lindos,"[[""Ojitos Lindos"", 97]]"
1,Bad Bunny,Rauw Alejandro,Directed,1398,NaN,NaN,1,94,Party,"[[""Party"", 94]]"
2,Bad Bunny,Jhay Cortez,Directed,1399,NaN,NaN,3,94,Tarot,"[[""Tarot"", 94], [""D\u00c1KITI"", 83], [""D\u00c1..."
3,Bad Bunny,Tony Dize,Directed,1400,NaN,NaN,1,91,La Corriente,"[[""La Corriente"", 91]]"
4,Bad Bunny,Tainy,Directed,1402,NaN,NaN,2,84,Callaita,"[[""Callaita"", 84], [""Callaita"", 81]]"

In [3]:
previews = pd.read_csv('./spotify-previews.csv')
previews = previews.loc[
    (previews['artists_coincides']) & (previews['track_name_conincides'])
]
previews.head()

,source,target,edge_track_name,spotify_track_name,spotify_artists,track_name_conincides,artists_coincides,id,preview
0,Bad Bunny,Bomba Estéreo,Ojitos Lindos,Ojitos Lindos,"Bad Bunny, Bomba Estéreo",True,True,3k3NWokhRRkEPhCzPmV8TW,https://p.scdn.co/mp3-preview/3cd0d6fb21cdca04...
1,Bad Bunny,Rauw Alejandro,Party,Party,"Bad Bunny, Rauw Alejandro",True,True,4tYFy8ALRjIZvnvSLw5lxN,https://p.scdn.co/mp3-preview/4982ab22ba534ab7...
2,Bad Bunny,Jhay Cortez,Tarot,Tarot,"Bad Bunny, Jhay Cortez",True,True,41oY4WCTj5kccfesTVFnvN,https://p.scdn.co/mp3-preview/db8db5f15768f239...
3,Bad Bunny,Tony Dize,La Corriente,La Corriente,"Bad Bunny, Tony Dize",True,True,1797zYiX4cKosMH836X9Gt,https://p.scdn.co/mp3-preview/5b652748ee9a5a10...
4,Bad Bunny,Tainy,Callaita,Callaita,"Bad Bunny, Tainy",True,True,71wFwRo8xGc4lrcyKwsvba,https://p.scdn.co/mp3-preview/dd0a3623872d32ea...

In [4]:
def getTrack(a1, a2):
    preview = previews.loc[(previews['source'] == a1) & (previews['target'] == a2), ['spotify_artists', 'preview']]
    if (len(preview.values) > 0):
        return preview.values[0]
    return ['', '']

In [5]:
edges_records = []
for i, edge in edges.iterrows():
    track = getTrack(edge['source'], edge['target'])
    record = {
        "source": edge['source'],
        "target": edge['target'],
        "weight": edge['weight'],
        "track_name": edge['colab_track_name'],
        "artists": track[0],
        "preview": track[1],
    }
    edges_records.append(record)

In [6]:
nodes = pd.read_csv('./nodes.csv')
nodes.head()

,id,label,interval,followers,popularity,id.1,componentnumber,strongcompnum,indegree,outdegree,unique_collabs,weighted_indegree,weighted_outdegree,total_collabs,eccentricity,closnesscentrality,harmonicclosnesscentrality,betweenesscentrality,modularity_class,pageranks
0,Bad Bunny,Bad Bunny,NaN,52296565,100,4q3ewBCX7sLwd24euuV69X,0,22,59,47,106,228,82,310,6,0.334160,0.394832,12840.180248,0,0.008945
1,Bomba Estéreo,Bomba Estéreo,NaN,969417,79,5n9bMYfz9qss2VOW89EVs2,0,22,2,3,5,2,5,7,8,0.265354,0.284921,1666.150781,5,0.000436
2,Rauw Alejandro,Rauw Alejandro,NaN,12796260,89,1mcTU81TzQhprhouKaTkpq,0,22,82,35,117,234,74,308,7,0.320800,0.373693,9155.825487,0,0.008404
3,Jhay Cortez,Jhay Cortez,NaN,4349987,84,0EFisYRi20PTADoJrifHrz,0,22,32,36,68,73,234,307,7,0.319886,0.373322,2552.074793,0,0.004053
4,Tony Dize,Tony Dize,NaN,2972734,75,3LKXWvXFWrkwUzJWxzwVpW,0,22,18,14,32,26,122,148,7,0.294323,0.333351,472.347037,1,0.002463

In [7]:
images = pd.read_csv('./images.csv')
images.head()

                       id                                          image_url
0  4q3ewBCX7sLwd24euuV69X  https://i.scdn.co/image/ab6761610000e5eb8ee9a6...
1  5n9bMYfz9qss2VOW89EVs2  https://i.scdn.co/image/ab6761610000e5ebcc4d7c...
2  1mcTU81TzQhprhouKaTkpq  https://i.scdn.co/image/ab6761610000e5eb75a694...
3  0EFisYRi20PTADoJrifHrz  https://i.scdn.co/image/ab6761610000e5ebbbeb7f...
4  3LKXWvXFWrkwUzJWxzwVpW  https://i.scdn.co/image/0fb75163d5836f4479ddc9...

In [8]:
def getImage(id):
    image = images.loc[images['id'] == id]
    if (len(image.values) > 0):
        return image.values[0][1]
    return ''

In [13]:
# Rename columns, merge with images
nodes_records = []
for i, node in nodes.iterrows():
    record = {
        "spotify_id": node['id.1'],
        "name_id": node['id'],
        "name": node['label'],
        "followers": node['followers'],
        "popularity": node['popularity'],
        "betweeness_centrality": node['betweenesscentrality'],
        "group": node['modularity_class'],
        "unique_collabs": node['unique_collabs'],
        "total_collabs": node['total_collabs'],
        "image": getImage(node['id.1'])
    }
    nodes_records.append(record)

In [14]:
nodes_df = pd.DataFrame(nodes_records)
nodes_df.to_csv('./nodes-full.csv')
nodes_df.head()

,spotify_id,name_id,name,followers,popularity,betweeness_centrality,group,unique_collabs,total_collabs,image
0,4q3ewBCX7sLwd24euuV69X,Bad Bunny,Bad Bunny,52296565,100,12840.180248,0,106,310,https://i.scdn.co/image/ab6761610000e5eb8ee9a6...
1,5n9bMYfz9qss2VOW89EVs2,Bomba Estéreo,Bomba Estéreo,969417,79,1666.150781,5,5,7,https://i.scdn.co/image/ab6761610000e5ebcc4d7c...
2,1mcTU81TzQhprhouKaTkpq,Rauw Alejandro,Rauw Alejandro,12796260,89,9155.825487,0,117,308,https://i.scdn.co/image/ab6761610000e5eb75a694...
3,0EFisYRi20PTADoJrifHrz,Jhay Cortez,Jhay Cortez,4349987,84,2552.074793,0,68,307,https://i.scdn.co/image/ab6761610000e5ebbbeb7f...
4,3LKXWvXFWrkwUzJWxzwVpW,Tony Dize,Tony Dize,2972734,75,472.347037,1,32,148,https://i.scdn.co/image/0fb75163d5836f4479ddc9...

In [15]:
edges_df = pd.DataFrame(edges_records)
edges_df.to_csv('./edges-full.csv')
edges_df.head()

,source,target,weight,track_name,artists,preview
0,Bad Bunny,Bomba Estéreo,1,Ojitos Lindos,"Bad Bunny, Bomba Estéreo",https://p.scdn.co/mp3-preview/3cd0d6fb21cdca04...
1,Bad Bunny,Rauw Alejandro,1,Party,"Bad Bunny, Rauw Alejandro",https://p.scdn.co/mp3-preview/4982ab22ba534ab7...
2,Bad Bunny,Jhay Cortez,3,Tarot,"Bad Bunny, Jhay Cortez",https://p.scdn.co/mp3-preview/db8db5f15768f239...
3,Bad Bunny,Tony Dize,1,La Corriente,"Bad Bunny, Tony Dize",https://p.scdn.co/mp3-preview/5b652748ee9a5a10...
4,Bad Bunny,Tainy,2,Callaita,"Bad Bunny, Tainy",https://p.scdn.co/mp3-preview/dd0a3623872d32ea...